version: '2.1'

services:
  chuck-producer:
    image: adoptopenjdk/openjdk11:alpine-jre
    depends_on:
      - kafka
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      SPRING_KAFKA_PROPERTIES_BOOTSTRAP_SERVERS: kafka:29092
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    volumes:
    - ./chuck-producer/build/libs/chuck-producer-0.0.1-SNAPSHOT.jar:/chuck-producer.jar

    entrypoint: ["java", "-jar", "chuck-producer.jar"]

  kafka:
    extends:
      file: dependencies-dev.yaml
      service: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092

  zookeeper:
    extends:
      file: dependencies-dev.yaml
      service: zookeeper
    depends_on:
      - portainer

  portainer:
    extends:
      file: dependencies-dev.yaml
      service: portainer

volumes:
  portainer_data:
